"""Add response_time_ms to request_logs

Revision ID: 05c676735ad8
Revises: be3aef3ba7b2
Create Date: 2025-02-11 13:56:19.734784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c676735ad8'
down_revision: Union[str, None] = 'be3aef3ba7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('response_time_ms', sa.Float(), nullable=True))
    op.drop_column('request_logs', 'tokens')
    op.drop_column('request_logs', 'token_per_second')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('token_per_second', sa.FLOAT(), nullable=True))
    op.add_column('request_logs', sa.Column('tokens', sa.INTEGER(), nullable=True))
    op.drop_column('request_logs', 'response_time_ms')
    # ### end Alembic commands ###
