"""Create request_logs table

Revision ID: be3aef3ba7b2
Revises: 
Create Date: 2025-02-11 11:52:31.784771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3aef3ba7b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('token_per_second', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_endpoint'), 'request_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_request_logs_id'), 'request_logs', ['id'], unique=False)
    op.create_index(op.f('ix_request_logs_model'), 'request_logs', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_model'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_endpoint'), table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###
